using '../main.bicep'

// =============================================================================
// Azure Global Lab — Default Parameter Values
//
// Usage:
//   az deployment sub create \
//     --location eastus \
//     --template-file main.bicep \
//     --parameters parameters/main.bicepparam
//
// Override individual parameters on the command line:
//   az deployment sub create \
//     --location eastus \
//     --template-file main.bicep \
//     --parameters parameters/main.bicepparam \
//     --parameters baseName='mylab' deploymentTier=1
// =============================================================================

// --- Required Parameters -----------------------------------------------------

param baseName = 'azlab'
param location = 'eastus'

// Admin password is auto-generated by deploy.ps1 and stored in Key Vault.
// When deploying via az CLI directly, pass it as a secure parameter:
//   --parameters adminPassword='YourSecureP@ssw0rd!'
param adminPassword = ''

// Domain name is prompted by deploy.ps1 at runtime.
// When deploying via az CLI directly, pass it as a parameter:
//   --parameters domainName='azlab.local'
param domainName = 'azlab.local'

// --- Deployment Tier ---------------------------------------------------------
// 1 = Core networking + AD (DCs, Bastion)
// 2 = + SQL Server VMs (4 VMs: CAS, PrimA, PrimB, PrimC)
// 3 = + Application VMs (CAS + 3 child primaries) — Full lab
param deploymentTier = 3

// --- Optional Overrides (uncomment to customize) -----------------------------

// --- Entra ID Integration (Hybrid Identity) ----------------------------------
// Enable to deploy Entra Connect Sync + Management VM with Entra ID login.
// Prerequisites: Entra ID tenant, Azure AD P2 license, Global Admin credentials.
// param enableEntraIntegration = true
// param entraIdDomain = 'usaavd.com'
// param domainStrategy = 'subdomain'          // 'subdomain' or 'independent'
// param entraConnectPlacement = 'dedicated'    // 'dedicated' or 'dc02'
// param vmNameMgmt = 'azlab-mgmt'
// param vmNameEntraConnect = 'azlab-aadcs'
// param sizeManagement = 'Standard_D2s_v6'

// param adminUsername = 'labadmin'

// param sizeDC = 'Standard_D2s_v6'
// param sizeApp = 'Standard_D4s_v6'
// param sizeSQL = 'Standard_D4s_v6'

// param vnetAddressPrefix = '10.0.0.0/16'
// param snetBastionPrefix = '10.0.0.0/26'
// param snetAdPrefix = '10.0.1.0/24'
// param snetMainPrefix = '10.0.20.0/24'
// param snetSite1Prefix = '10.0.30.0/24'
// param snetSite2Prefix = '10.0.40.0/24'

// param dc01Ip = '10.0.1.4'
// param dc02Ip = '10.0.1.5'
// param dcMainIp = '10.0.20.250'
// param dcSite1Ip = '10.0.30.250'
// param dcSite2Ip = '10.0.40.250'

// param vmNameDcMain = 'azlab-dc03'
// param vmNameDcSite1 = 'azlab-dc04'
// param vmNameDcSite2 = 'azlab-dc05'

// param imagePublisher = 'MicrosoftWindowsServer'
// param imageOffer = 'WindowsServer'
// param imageSku = '2025-datacenter-g2'   // Allowed: '2025-datacenter-g2' (default), '2022-datacenter-g2'

// param envTag = 'lab'
